server:
  port: 8090

spring:
  application:
    name: goods-store-web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        file-extension: yaml
        namespace: public
  config:
    import:
      - optional:nacos:goods-store-common.yaml

snowflake:
  worker-id: 7
  datacenter-id: 1
